### ISSUE TITLE
RestrictedSink does not forward ISetLoggingFailureListener to inner sink

### ISSUE THREAD

**Issue by ArieGato** [serilog/serilog#2231]
**Description**

`Serilog.Core.Sinks.RestrictedSink` — the wrapper applied by `LoggerSinkConfiguration.Sink(sink, restrictedToMinimumLevel)` whenever `restrictedToMinimumLevel` is anything other than `LevelAlias.Minimum` — does not implement `ISetLoggingFailureListener`. As a result, when an inner sink supports `ISetLoggingFailureListener` (directly or via `BatchingSink`), the failure listener installed by `FailureListenerSink` (used internally by `WriteTo.FallbackChain(...)` and `WriteTo.Fallible(...)`, introduced in #2108) never reaches it.

For synchronous sinks the gap is masked: `FailureListenerSink.Emit(...)` catches exceptions and notifies the listener directly. For **async/batched sinks** that surface failures only through `ILoggingFailureListener` (notably anything built on `Serilog.Core.Sinks.Batching.BatchingSink`), the listener stays unset and failed batches are silently dropped via `SelfLog` instead of being routed to the next stage of a fallback chain.

The companion wrapper `OptionalInterfaceForwardingSink` already forwards `ISetLoggingFailureListener` correctly — `RestrictedSink` should do the same.

**Reproduction**

```csharp
var listener = new MyFailureListener();

var log = new LoggerConfiguration()
    .WriteTo.FallbackChain(
        // Primary: a batching sink with RestrictedToMinimumLevel set
        wt => wt.MyBatchingSink(restrictedToMinimumLevel: LogEventLevel.Information),
        // Fallback
        wt => wt.File("fallback.log"))
    .CreateLogger();

// When the primary batching sink fails to flush a batch, the failure is
// SelfLog'd and dropped. The fallback never receives the events because
// the listener was never installed on the batching sink — RestrictedSink
// swallowed the SetFailureListener call.
```

Removing `restrictedToMinimumLevel` (or using `LevelAlias.Minimum`) makes the fallback work as expected, because no `RestrictedSink` wrap is created.

**Expected behavior**

`RestrictedSink` should forward `SetFailureListener` to its inner sink when that sink implements `ISetLoggingFailureListener`, mirroring the forwarding already done by `OptionalInterfaceForwardingSink`.

**Relevant package, tooling and runtime versions**

- Serilog `dev` (4.3.2), reproduced on `net8.0` and `net9.0`.
- Discovered while wiring `Serilog.Sinks.RabbitMQ` against the new `WriteTo.FallbackChain` / `WriteTo.Fallible` extensions from #2108.

**Additional context**

Happy to open a PR — the fix is one method (mirror of `OptionalInterfaceForwardingSink.SetFailureListener`) plus a regression test.
